apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sysop@serenitylabs.cloud
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
      providers:
        - name: cloudflare
          cloudflare:
            email: sysop@serenitylabs.cloud
            apiKeySecretRef:
              name: cloudflare-api
              namespace: cert-manager
              key: CF_API_KEY
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: sysop@serenitylabs.cloud
    privateKeySecretRef:
      name: letsencrypt-staging
    dns01:
      providers:
        - name: cloudflare
          cloudflare:
            email: sysop@serenitylabs.cloud
            apiKeySecretRef:
              name: cloudflare-api
              namespace: cert-manager
              key: CF_API_KEY
    http01: {}