apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: pgadmin-tq-slis-icu
  namespace: mastodon-common
spec:
  secretName: pgadmin-tq-slis-icu
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: pgadmin.tq.slis.icu
  dnsNames:
  - pgadmin.tq.slis.icu
  acme:
    config:
    - dns01:
        provider: cloudflare
      domains:
      - 'pgadmin.tq.slis.icu'