apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: files-slis-icu
  namespace: mastodon-common
spec:
  secretName: files-slis-icu
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: files.slis.icu
  dnsNames:
  - files.slis.icu
  acme:
    config:
    - dns01:
        provider: cloudflare
      domains:
      - 'files.slis.icu'