apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  SMTP_PASSWORD: ""
  SECRET_KEY_BASE: ""
  OTP_SECRET: ""
  VAPID_PRIVATE_KEY: ""
  VAPID_PUBLIC_KEY: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: aws
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""