apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres
spec:
  version: "10.2-v1"
  replicas: 1
  doNotPause: true
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
