apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis
spec:
  version: "4-v1"
  replicas: 1
  doNotPause: true
  storage:
    storageClassName: "block-unreplicated"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
