apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: example-org
spec:
  secretName: example-org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: example.org
  dnsNames:
  - example.org
  - www.example.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - example.org
      - www.example.org
