apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mastodon-sidekiq
  labels:
    app: mastodon-sidekiq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mastodon-sidekiq
    spec:
      containers:
      - name: sidekiq
        image: gargron/mastodon:v2.5.0
        command: ["/bin/ash", "-c", "bundle exec sidekiq -q default -q mailers -q pull -q push"]
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: config
        - secretRef:
            name: secrets
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-auth
              key: POSTGRES_PASSWORD
        resources:
          requests:
            memory: 350Mi
            cpu: 100m